- name: Copy all game textures to root for web editor
        run: |
          # Check if the deep textures directory exists
          if [ -d "textures/resource_pack/textures" ]; then
            echo "Copying textures to root folder..."
            # Copy all folders and files from inside the deep textures folder into the root
            cp -r textures/resource_pack/textures/* ./
          else
            echo "Error: Texture folder path not found!"
            exit 1
          fi
